[package]
name = "mgs"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
cipher = "0.4.4"
clap = { version = "4.5.6", features = ["derive"] }
hex = "0.4.3"
hmac = "0.12.1"
pbkdf2 = "0.12.2"
rand = "0.8.5"
ring = "0.17.8"
rpassword = "7.3.1"
sha2 = "0.10.8"
tiny-bip39 = "1.0.0"
